# Generated by Django 3.0.7 on 2020-07-12 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200711_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='PostFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='post/file')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.Post')),
            ],
            options={
                'db_table': 'tbl_post_files',
            },
        ),
    ]
