# Generated by Django 3.0.7 on 2020-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20200712_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
