# Generated by Django 3.0.7 on 2020-07-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200713_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
